/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.text.MessageFormat;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP Gaming
 */
public class MenuDetailForm extends javax.swing.JFrame {

    /**
     * Creates new form ChasierForm
     */
    public MenuDetailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pesanan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_makanan = new javax.swing.JLabel();
        btnKentangGoreng = new javax.swing.JButton();
        btnRotiBakar = new javax.swing.JButton();
        btnIndomieGoreng = new javax.swing.JButton();
        btnWaffle = new javax.swing.JButton();
        btnBurger = new javax.swing.JButton();
        btnSpagetti = new javax.swing.JButton();
        btnOnionRing = new javax.swing.JButton();
        btnSosisGoreng = new javax.swing.JButton();
        btnNasiGoreng = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnDimsum = new javax.swing.JButton();
        pnl_Total = new javax.swing.JPanel();
        lbl_total = new javax.swing.JLabel();
        lbl_subtotal = new javax.swing.JLabel();
        lbl_tax = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_subtotal = new javax.swing.JTextField();
        txt_tax = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl_minuman = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnChocoLatte = new javax.swing.JButton();
        btnVanillaLatte = new javax.swing.JButton();
        btnIceTea = new javax.swing.JButton();
        btnLycheeTea = new javax.swing.JButton();
        btnMatchaLatte = new javax.swing.JButton();
        btnTaroLatte = new javax.swing.JButton();
        btnAmericano = new javax.swing.JButton();
        btnRedVelvetLatte = new javax.swing.JButton();
        btnCoffeeLatte = new javax.swing.JButton();
        btnLemonTea = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnProses = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        tbl_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ));
        jScrollPane2.setViewportView(tbl_pesanan);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lbl_makanan.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        lbl_makanan.setText("MAKANAN");

        btnKentangGoreng.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnKentangGoreng.setText("Kentang Goreng");
        btnKentangGoreng.setPreferredSize(new java.awt.Dimension(135, 25));

        btnRotiBakar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnRotiBakar.setText("Roti Bakar");

        btnIndomieGoreng.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnIndomieGoreng.setText("Indomie Goreng");

        btnWaffle.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnWaffle.setText("Waffle");
        btnWaffle.setPreferredSize(new java.awt.Dimension(135, 25));

        btnBurger.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnBurger.setText("Burger");

        btnSpagetti.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnSpagetti.setText("Spagetti");

        btnOnionRing.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnOnionRing.setText("Onion Ring");

        btnSosisGoreng.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnSosisGoreng.setText("Sosis Goreng");

        btnNasiGoreng.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnNasiGoreng.setText("Nasi Goreng");

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));

        btnDimsum.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnDimsum.setText("Dimsum");
        btnDimsum.setPreferredSize(new java.awt.Dimension(135, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIndomieGoreng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDimsum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSpagetti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnWaffle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOnionRing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnSosisGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnKentangGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRotiBakar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(lbl_makanan)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_makanan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKentangGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRotiBakar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIndomieGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWaffle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDimsum, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpagetti, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOnionRing, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSosisGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        pnl_Total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnl_Total.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_total.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lbl_total.setText("TOTAL");
        pnl_Total.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, 30));

        lbl_subtotal.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lbl_subtotal.setText("SUB TOTAL");
        pnl_Total.add(lbl_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 30));

        lbl_tax.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lbl_tax.setText("TAX");
        pnl_Total.add(lbl_tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 30));

        txt_total.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pnl_Total.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, 30));

        txt_subtotal.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pnl_Total.add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 150, 30));

        txt_tax.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        pnl_Total.add(txt_tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 150, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_minuman.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        lbl_minuman.setText("MINUMAN");
        jPanel3.add(lbl_minuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 44));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 413, 10));

        btnChocoLatte.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnChocoLatte.setText("Choco Latte");
        jPanel3.add(btnChocoLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, 53));

        btnVanillaLatte.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnVanillaLatte.setText("Vanilla Latte");
        jPanel3.add(btnVanillaLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 130, 53));

        btnIceTea.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnIceTea.setText("Ice Tea");
        jPanel3.add(btnIceTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 53));

        btnLycheeTea.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnLycheeTea.setText("Lychee Tea");
        jPanel3.add(btnLycheeTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, 53));

        btnMatchaLatte.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnMatchaLatte.setText("Matcha Latte");
        jPanel3.add(btnMatchaLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 130, 53));

        btnTaroLatte.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnTaroLatte.setText("Taro Latte");
        jPanel3.add(btnTaroLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 53));

        btnAmericano.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        btnAmericano.setText("Americano Coffee");
        jPanel3.add(btnAmericano, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 53));

        btnRedVelvetLatte.setFont(new java.awt.Font("Georgia", 0, 13)); // NOI18N
        btnRedVelvetLatte.setText("Red Velvet Latte");
        jPanel3.add(btnRedVelvetLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, 53));

        btnCoffeeLatte.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnCoffeeLatte.setText("Coffee Latte");
        jPanel3.add(btnCoffeeLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, 53));

        btnLemonTea.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnLemonTea.setText("Lemon Tea");
        jPanel3.add(btnLemonTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 130, 53));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnRemove.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnRemove.setText("REMOVE");

        btnReset.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnReset.setText("RESET");

        btnProses.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnProses.setText("PROSESS");

        btnPay.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnPay.setText("PAY");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProses, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setText("SMART CAFE");

        jLabel2.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel2.setText("Menu Detail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(492, 492, 492))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(573, 573, 573))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnl_Total, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //=========================== function ITEM COST =======================================
    
    public  JTable getTablePesanan(){
        return tbl_pesanan;
    }
    
    public void tambahBaris(Object[] o){
        
    }
    
    public JTextField getTxtSubtotal() {
        return txt_subtotal;
    }
    
    public JTextField getTxtTax() {
        return txt_tax;
    }
    
    public JTextField getTxtTotal() {
        return txt_total;
    }
    
    public JButton getBtnKentang() {
        return btnKentangGoreng;
    }
    
    public void btnKentang (ActionListener ac){
        btnKentangGoreng.addActionListener(ac);
    }
    
    public void btnRoti (ActionListener ac) {
        btnRotiBakar.addActionListener(ac);
    }
    
    public void btnIndomieGoreng (ActionListener ac) {
        btnIndomieGoreng.addActionListener(ac);
    }
    
    public void btnDimsum (ActionListener ac) {
        btnDimsum.addActionListener(ac);
    }
    
    public void btnWaffle (ActionListener ac) {
        btnWaffle.addActionListener(ac);
    }
    
    public void btnBurger (ActionListener ac) {
        btnBurger.addActionListener(ac);
    }
    
    public void btnSpagetti (ActionListener ac) {
        btnSpagetti.addActionListener(ac);
    }
    
    public void btnOnion (ActionListener ac) {
        btnOnionRing.addActionListener(ac);
    }
    
    public void btnSosis (ActionListener ac) {
        btnSosisGoreng.addActionListener(ac);
    }
    
    public void btnNasGor (ActionListener ac) {
        btnNasiGoreng.addActionListener(ac);
    }
 //============MINUMAN=========
    
    
    public void btnAmericano (ActionListener ac) {
        btnAmericano.addActionListener(ac);
    }
    
    public void btnCoffee (ActionListener ac) {
        btnCoffeeLatte.addActionListener(ac);
    } 
    
    public void btnIceTea (ActionListener ac) {
        btnIceTea.addActionListener(ac);
    }
    
    public void btnLychee (ActionListener ac) {
        btnLycheeTea.addActionListener(ac);
    }
    
    public void btnLemon (ActionListener ac) {
        btnLemonTea.addActionListener(ac);
    }
    
    public void btnTaro (ActionListener ac) {
        btnTaroLatte.addActionListener(ac);
    }
    
    public void btnMatcha (ActionListener ac) {
        btnMatchaLatte.addActionListener(ac);
    }
    
    public void btnRedVelvet (ActionListener ac) {
        btnRedVelvetLatte.addActionListener(ac);
    }
    
    public void btnVanilla (ActionListener ac) {
        btnVanillaLatte.addActionListener(ac);
    }
    
    public void btnChoco (ActionListener ac) {
        btnChocoLatte.addActionListener(ac);
    }
    
    public void btnReset (ActionListener ac) {
        btnReset.addActionListener(ac);
    } 
    
    public void btnRemove (ActionListener ac) {
        btnRemove.addActionListener(ac);
    }
    
    public void btnPay (ActionListener ac) {
        btnPay.addActionListener(ac);
    }
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDetailForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmericano;
    private javax.swing.JButton btnBurger;
    private javax.swing.JButton btnChocoLatte;
    private javax.swing.JButton btnCoffeeLatte;
    private javax.swing.JButton btnDimsum;
    private javax.swing.JButton btnIceTea;
    private javax.swing.JButton btnIndomieGoreng;
    private javax.swing.JButton btnKentangGoreng;
    private javax.swing.JButton btnLemonTea;
    private javax.swing.JButton btnLycheeTea;
    private javax.swing.JButton btnMatchaLatte;
    private javax.swing.JButton btnNasiGoreng;
    private javax.swing.JButton btnOnionRing;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnRedVelvetLatte;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnRotiBakar;
    private javax.swing.JButton btnSosisGoreng;
    private javax.swing.JButton btnSpagetti;
    private javax.swing.JButton btnTaroLatte;
    private javax.swing.JButton btnVanillaLatte;
    private javax.swing.JButton btnWaffle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_makanan;
    private javax.swing.JLabel lbl_minuman;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JLabel lbl_tax;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JPanel pnl_Total;
    private javax.swing.JTable tbl_pesanan;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_tax;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
